#!/bin/sh

echo "Script $0 triggered ..."

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
echo "Starting ruff analysis..."

# quietly run ruff
ruff . --fix

# report failing ruff analysis
# because ruff is run on all files, not just those in the commit,
# we do not abort the commit, but instead show how to recommit if the user desires.
if [ $? != "0" ]; then
    echo "\033[1mRuff analysis failed!"
    echo "Recommend fixing ruff errors and recommitting (git commit --amend)\033[0m"
else
    echo "Pre-commit checks completed successfully."
fi
